export interface ScreenerColumnVisibility {
  symbol: boolean;
  price: boolean;
  changePercent: boolean;
  volume: boolean;
  relVol: boolean;
  marketCap: boolean;
  sector: boolean;
  beta: boolean;
  recommendedOutlook: boolean;
  opportunityScore: boolean;
}

export interface AppSettings {
  // General
  defaultPage: string;
  timezone: string;
  dateFormat: string;
  numberFormat: string;
  autoRefresh: boolean;
  autoRefreshInterval: number;
  // Trading Defaults
  defaultDTE: number;
  minDTE: number;
  maxDTE: number;
  defaultContracts: number;
  defaultOrderType: string;
  slippageTolerance: number;
  confirmOrders: boolean;
  preferEvenLots: boolean;
  // Risk Management
  maxPositionPct: number;
  maxPortfolioRisk: number;
  maxSingleLoss: number;
  stopLossPct: number;
  marginBuffer: number;
  maxOpenPositions: number;
  enforceRiskLimits: boolean;
  // Screener
  screenerColumnVisibility: ScreenerColumnVisibility;
  minOpportunityScoreToShow: number;
  highConvictionOpportunityScore: number;
  highConvictionTechnicalScore: number;
  highConvictionIvScore: number;
  highConvictionEntryScore: number;
  highConvictionMomentumScore: number;
  screenerDefaultSortColumn: string;
  screenerDefaultSortDirection: "asc" | "desc";
  screenerDefaultPreset: string;
  screenerDefaultLiquidity: string;
  screenerDefaultOutlook: string;
  showScoreBreakdownTooltip: boolean;
  showSetupTypeBadge: boolean;
  showRecommendationBadge: boolean;
  defaultMinIvRank: number;
  defaultMinVolume: number;
  defaultMinMarketCap: string;
  defaultMinOpportunityScore: number;
  includeETFs: boolean;
  includeIndices: boolean;
  minPrice: number;
  maxPrice: number;
  minLiquidity: string;
  screenerRowsPerPage: number;
  screenerDefaultTab: string;
  showSectorBadge: boolean;
  showOutlookBadge: boolean;
  showConvictionBadges: boolean;
  // Dashboard
  dashboardRefreshInterval: number;
  showMarketHoursIndicator: boolean;
  dashboardCompactCards: boolean;
  moverCount: number;
  showBreadthBar: boolean;
  defaultChartPeriod: string;
  // Options Chain
  defaultMinDelta: number;
  defaultMaxDelta: number;
  maxBidAskSpread: number;
  minOpenInterest: number;
  showWeeklyExp: boolean;
  chainStrikeRange: number;
  highlightITM: boolean;
  showGreeks: boolean;
  rsiOverbought: number;
  rsiOversold: number;
  // Strategy
  preferredStrategies: string[];
  minCredit: number;
  targetProfitPct: number;
  maxLossMultiplier: number;
  showProbabilityOfProfit: boolean;
  useTheoreticalValue: boolean;
  // Portfolio & P&L
  pnlMethod: string;
  benchmark: string;
  showUnrealizedPnl: boolean;
  showRealizedPnl: boolean;
  taxMethod: string;
  showPortfolioDelta: boolean;
  showPortfolioTheta: boolean;
  // Alerts
  browserNotifications: boolean;
  soundAlerts: boolean;
  toastDuration: number;
  ivRankAlertThreshold: number;
  priceMoveAlertPct: number;
  pnlAlertThreshold: number;
  expiryWarningDays: number;
  earningsAlertDays: number;
  // Appearance
  theme: string;
  uiDensity: string;
  fontSize: string;
  chartStyle: string;
  animateTransitions: boolean;
  showMiniCharts: boolean;
  tableRowHeight: string;
  sidebarDefaultOpen: boolean;
  // Data & Sources
  universeMode: string;
  cacheRefreshInterval: number;
  showDataSourceTags: boolean;
  polygonRefreshRate: number;
  marketDataSource: string;
  screenerUniverseSize: number;
  enablePreMarket: boolean;
  enableAfterHours: boolean;
  cacheStrategy: string;
  // Advanced / Security
  debugMode: boolean;
  apiTimeout: number;
  logLevel: string;
  disableStreamer: boolean;
  // Time Horizon
  earningsBlackoutDays: number;
  // Chart & Analysis
  defaultChartIndicators: string[];
  showVolumeOnChart: boolean;
  candleInterval: string;
  // Watchlist
  watchlistDefaultSort: string;
  watchlistShowIVRank: boolean;
  watchlistShowEarnings: boolean;
  watchlistShowDailyChange: boolean;
  // Positions
  positionsGroupBy: string;
  positionsDefaultSort: string;
  autoCloseAtExpiry: boolean;
}

export const SETTING_DEFAULTS: AppSettings = {
  // General
  defaultPage: "/",
  timezone: "ET",
  dateFormat: "MM/DD/YYYY",
  numberFormat: "US",
  autoRefresh: true,
  autoRefreshInterval: 60,
  // Trading Defaults
  defaultDTE: 45,
  minDTE: 7,
  maxDTE: 90,
  defaultContracts: 1,
  defaultOrderType: "limit",
  slippageTolerance: 5,
  confirmOrders: true,
  preferEvenLots: false,
  // Risk Management
  maxPositionPct: 5,
  maxPortfolioRisk: 20,
  maxSingleLoss: 500,
  stopLossPct: 50,
  marginBuffer: 20,
  maxOpenPositions: 10,
  enforceRiskLimits: true,
  // Screener
  screenerColumnVisibility: {
    symbol: true,
    price: true,
    changePercent: true,
    volume: true,
    relVol: true,
    marketCap: true,
    sector: true,
    beta: true,
    recommendedOutlook: true,
    opportunityScore: true,
  },
  minOpportunityScoreToShow: 0,
  highConvictionOpportunityScore: 75,
  highConvictionTechnicalScore: 20,
  highConvictionIvScore: 15,
  highConvictionEntryScore: 15,
  highConvictionMomentumScore: 8,
  screenerDefaultSortColumn: "marketCap",
  screenerDefaultSortDirection: "desc",
  screenerDefaultPreset: "All",
  screenerDefaultLiquidity: "all",
  screenerDefaultOutlook: "all",
  showScoreBreakdownTooltip: true,
  showSetupTypeBadge: true,
  showRecommendationBadge: true,
  defaultMinIvRank: 30,
  defaultMinVolume: 500000,
  defaultMinMarketCap: "1B",
  defaultMinOpportunityScore: 50,
  includeETFs: true,
  includeIndices: false,
  minPrice: 5,
  maxPrice: 0,
  minLiquidity: "medium",
  screenerRowsPerPage: 100,
  screenerDefaultTab: "overview",
  showSectorBadge: true,
  showOutlookBadge: true,
  showConvictionBadges: true,
  // Dashboard
  dashboardRefreshInterval: 60,
  showMarketHoursIndicator: true,
  dashboardCompactCards: false,
  moverCount: 5,
  showBreadthBar: true,
  defaultChartPeriod: "1M",
  // Options Chain
  defaultMinDelta: 0.1,
  defaultMaxDelta: 0.5,
  maxBidAskSpread: 0.5,
  minOpenInterest: 100,
  showWeeklyExp: true,
  chainStrikeRange: 10,
  highlightITM: true,
  showGreeks: true,
  rsiOverbought: 70,
  rsiOversold: 30,
  // Strategy
  preferredStrategies: ["Short Put", "Iron Condor"],
  minCredit: 0.5,
  targetProfitPct: 50,
  maxLossMultiplier: 2,
  showProbabilityOfProfit: true,
  useTheoreticalValue: false,
  // Portfolio & P&L
  pnlMethod: "mark",
  benchmark: "SPY",
  showUnrealizedPnl: true,
  showRealizedPnl: true,
  taxMethod: "FIFO",
  showPortfolioDelta: true,
  showPortfolioTheta: true,
  // Alerts
  browserNotifications: false,
  soundAlerts: false,
  toastDuration: 3000,
  ivRankAlertThreshold: 60,
  priceMoveAlertPct: 5,
  pnlAlertThreshold: 1000,
  expiryWarningDays: 7,
  earningsAlertDays: 5,
  // Appearance
  theme: "dark",
  uiDensity: "comfortable",
  fontSize: "medium",
  chartStyle: "line",
  animateTransitions: true,
  showMiniCharts: false,
  tableRowHeight: "default",
  sidebarDefaultOpen: true,
  // Data & Sources
  universeMode: "polygon",
  cacheRefreshInterval: 30 * 60 * 1000,
  showDataSourceTags: true,
  polygonRefreshRate: 30,
  marketDataSource: "auto",
  screenerUniverseSize: 1000,
  enablePreMarket: false,
  enableAfterHours: false,
  cacheStrategy: "moderate",
  // Advanced / Security
  debugMode: false,
  apiTimeout: 15000,
  logLevel: "warn",
  disableStreamer: false,
  // Time Horizon
  earningsBlackoutDays: 3,
  // Chart & Analysis
  defaultChartIndicators: ["SMA20", "SMA50"],
  showVolumeOnChart: true,
  candleInterval: "1D",
  // Watchlist
  watchlistDefaultSort: "symbol",
  watchlistShowIVRank: true,
  watchlistShowEarnings: true,
  watchlistShowDailyChange: true,
  // Positions
  positionsGroupBy: "none",
  positionsDefaultSort: "openDate",
  autoCloseAtExpiry: false,
};
