export interface ScreenerColumnVisibility {
  symbol: boolean;
  price: boolean;
  changePercent: boolean;
  volume: boolean;
  relVol: boolean;
  marketCap: boolean;
  sector: boolean;
  beta: boolean;
  recommendedOutlook: boolean;
  opportunityScore: boolean;
}

export interface AppSettings {
  // General
  defaultPage: string;
  timezone: string;
  dateFormat: string;
  numberFormat: string;
  autoRefresh: boolean;
  autoRefreshInterval: number;
  // Trading Defaults
  defaultDTE: number;
  minDTE: number;
  maxDTE: number;
  defaultContracts: number;
  defaultOrderType: string;
  slippageTolerance: number;
  confirmOrders: boolean;
  preferEvenLots: boolean;
  // Risk Management
  maxPositionPct: number;
  maxPortfolioRisk: number;
  maxSingleLoss: number;
  stopLossPct: number;
  marginBuffer: number;
  maxOpenPositions: number;
  enforceRiskLimits: boolean;
  maxCapitalPerTrade: number;
  maxTotalCapitalDeployedPct: number;
  maxLossPerTradePct: number;
  maxPortfolioDrawdownPct: number;
  dailyLossLimit: number;
  maxPositionsPerSector: number;
  maxPositionsPerUnderlying: number;
  maxLosingPositions: number;
  riskMinDTE: number;
  riskMaxDTE: number;
  earningsAvoidanceDays: number;
  minContractVolume: number;
  maxBidAskSpreadPct: number;
  showRiskWarnings: boolean;
  showPositionSizingSuggestion: boolean;
  portfolioSize: number;
  // Screener
  screenerColumnVisibility: ScreenerColumnVisibility;
  minOpportunityScoreToShow: number;
  highConvictionOpportunityScore: number;
  highConvictionTechnicalScore: number;
  highConvictionIvScore: number;
  highConvictionEntryScore: number;
  highConvictionMomentumScore: number;
  screenerDefaultSortColumn: string;
  screenerDefaultSortDirection: "asc" | "desc";
  screenerDefaultPreset: string;
  screenerDefaultLiquidity: string;
  screenerDefaultOutlook: string;
  showScoreBreakdownTooltip: boolean;
  showSetupTypeBadge: boolean;
  showRecommendationBadge: boolean;
  defaultMinIvRank: number;
  defaultMinVolume: number;
  defaultMinMarketCap: string;
  defaultMinOpportunityScore: number;
  includeETFs: boolean;
  includeIndices: boolean;
  minPrice: number;
  maxPrice: number;
  minLiquidity: string;
  screenerRowsPerPage: number;
  screenerDefaultTab: string;
  showSectorBadge: boolean;
  showOutlookBadge: boolean;
  showConvictionBadges: boolean;
  // Dashboard
  dashboardRefreshInterval: number;
  showMarketHoursIndicator: boolean;
  dashboardCompactCards: boolean;
  moverCount: number;
  showBreadthBar: boolean;
  defaultChartPeriod: string;
  // Options Chain
  defaultMinDelta: number;
  defaultMaxDelta: number;
  maxBidAskSpread: number;
  minOpenInterest: number;
  showWeeklyExp: boolean;
  chainStrikeRange: number;
  highlightITM: boolean;
  showGreeks: boolean;
  showDelta: boolean;
  showGamma: boolean;
  showTheta: boolean;
  showVega: boolean;
  showRho: boolean;
  greeksPrecision: number;
  showPortfolioGreeksSummary: boolean;
  greeksDisplayFormat: string;
  shortPutDeltaMin: number;
  shortPutDeltaMax: number;
  shortCallDeltaMin: number;
  shortCallDeltaMax: number;
  longOptionDeltaMin: number;
  longOptionDeltaMax: number;
  highlightOutsideTargetDelta: boolean;
  showDeltaAsProbabilityItm: boolean;
  ivDisplayFormat: string;
  showIvRankAlongsideIv: boolean;
  showIvPercentileAlongsideIvRank: boolean;
  ivRankCalculationPeriod: string;
  highlightHighIvStocks: boolean;
  highIvHighlightThreshold: number;
  defaultExpirationCount: number;
  showOpenInterestColumn: boolean;
  showVolumeColumn: boolean;
  showBidAskSpreadColumn: boolean;
  showTheoreticalValueColumn: boolean;
  filterIlliquidOptionsAutomatically: boolean;
  showDailyThetaDecay: boolean;
  showThetaAsDollarsPerDay: boolean;
  showThetaDecayCurve: boolean;
  thetaDecayWarningThresholdDte: number;
  rsiOverbought: number;
  rsiOversold: number;
  // Strategy
  enabledStrategyIds: Record<string, boolean>;
  strategyDefaultOutlook: string;
  strategyDefaultTier: string;
  strategyDefaultStrategyId: string;
  preferredIvEnvironment: string;
  ivRankLowThreshold: number;
  ivRankHighThreshold: number;
  strategyAutoSelectByIv: boolean;
  ivScoreWeight: number;
  technicalScoreWeight: number;
  entryScoreWeight: number;
  momentumScoreWeight: number;
  vwapScoreWeight: number;
  preferredStrategies: string[];
  minCredit: number;
  targetProfitPct: number;
  maxLossMultiplier: number;
  showProbabilityOfProfit: boolean;
  useTheoreticalValue: boolean;
  // Portfolio & P&L
  pnlMethod: string;
  commissionPerContract: number;
  perLegCommission: number;
  exchangeFeePerContract: number;
  includeCommissionsInPnl: boolean;
  includeFeesInBreakeven: boolean;
  contractMultiplier: number;
  pnlDisplayMode: string;
  showMaxProfitOnPnlCurve: boolean;
  showMaxLossOnPnlCurve: boolean;
  showBreakevenOnPnlCurve: boolean;
  showCurrentPriceOnPnlCurve: boolean;
  pnlCurveResolution: number;
  scenarioUnderlyingMovePct: number;
  scenarioIvChangePct: number;
  scenarioDteStepDays: number;
  showGreeksImpactInScenario: boolean;
  defaultProfitTargetPct: number;
  defaultStopLossPct: number;
  showProfitTargetLine: boolean;
  showStopLossLine: boolean;
  autoCalculateProfitTarget: boolean;
  defaultIvAssumption: string;
  riskFreeRatePct: number;
  dividendYieldAssumptionPct: number;
  useHistoricalVolatilityForSimulation: boolean;
  benchmark: string;
  showUnrealizedPnl: boolean;
  showRealizedPnl: boolean;
  taxMethod: string;
  showPortfolioDelta: boolean;
  showPortfolioTheta: boolean;
  // Alerts
  browserNotifications: boolean;
  soundAlerts: boolean;
  toastDuration: number;
  ivRankAlertThreshold: number;
  priceMoveAlertPct: number;
  pnlAlertThreshold: number;
  expiryWarningDays: number;
  earningsAlertDays: number;
  // Appearance
  theme: string;
  uiDensity: string;
  fontSize: string;
  chartStyle: string;
  animateTransitions: boolean;
  showMiniCharts: boolean;
  tableRowHeight: string;
  sidebarDefaultOpen: boolean;
  // Data & Sources
  universeMode: string;
  cacheRefreshInterval: number;
  showDataSourceTags: boolean;
  polygonRefreshRate: number;
  marketDataSource: string;
  screenerUniverseSize: number;
  enablePreMarket: boolean;
  enableAfterHours: boolean;
  cacheStrategy: string;
  // Advanced / Security
  debugMode: boolean;
  apiTimeout: number;
  logLevel: string;
  disableStreamer: boolean;
  // Time Horizon
  earningsBlackoutDays: number;
  showDteRangeFilterDefault: boolean;
  preferredExpirationCycles: string[];
  highlightPreferredExpirationCycles: boolean;
  warnOutsidePreferredExpirationCycle: boolean;
  earningsAvoidanceBeforeDays: number;
  earningsAvoidanceAfterDays: number;
  showEarningsDateColumnDefault: boolean;
  showEarningsWarningBadge: boolean;
  allowEarningsAvoidanceOverride: boolean;
  thetaOpenMinDTE: number;
  thetaOpenMaxDTE: number;
  thetaCloseProfitPct: number;
  thetaCloseDTE: number;
  showThetaDecayChart: boolean;
  avoidMondayMorningEntries: boolean;
  avoidFridayAfternoonEntries: boolean;
  preferredTradingWindowStart: string;
  preferredTradingWindowEnd: string;
  // Chart & Analysis
  defaultChartIndicators: string[];
  showVolumeOnChart: boolean;
  candleInterval: string;
  chartHeight: string;
  autoFitChartToPrice: boolean;
  showSMA20: boolean;
  sma20Color: string;
  showSMA50: boolean;
  sma50Color: string;
  showSMA200: boolean;
  sma200Color: string;
  showEMA9: boolean;
  ema9Color: string;
  showEMA21: boolean;
  ema21Color: string;
  showVWAPLine: boolean;
  vwapColor: string;
  showSupportResistanceLines: boolean;
  showBollingerBands: boolean;
  showRsiPanel: boolean;
  showMacdPanel: boolean;
  showAtrPanel: boolean;
  show52WeekHighLowLines: boolean;
  showEarningsMarkersOnChart: boolean;
  showStrategyPriceLevels: boolean;
  showPositionPnlOverlay: boolean;
  showBreakevenLines: boolean;
  // Watchlist
  maxWatchlistSize: number;
  showWatchlistSizeWarning: boolean;
  watchlistSizeWarningThresholdPct: number;
  allowDuplicateWatchlistSymbols: boolean;
  autoRemoveLowScoreWatchlistSymbols: boolean;
  autoRemoveWatchlistScoreThreshold: number;
  watchlistDefaultSort: string;
  watchlistDefaultSortDirection: "asc" | "desc";
  watchlistShowOpportunityScore: boolean;
  watchlistShowSetupTypeBadge: boolean;
  watchlistShowLastUpdated: boolean;
  watchlistShowIVRank: boolean;
  watchlistShowEarnings: boolean;
  watchlistShowDailyChange: boolean;
  compactWatchlistView: boolean;
  autoAddHighConvictionToWatchlist: boolean;
  autoAddWatchlistOpportunityThreshold: number;
  autoAddOnlyPreferredStrategies: boolean;
  maxWatchlistAutoAddsPerDay: number;
  notifyOnWatchlistAutoAdd: boolean;
  alertWatchlistScoreDrop: boolean;
  watchlistScoreDropAlertThreshold: number;
  watchlistEarningsAlertDays: number;
  watchlistIvSpikeAlertThreshold: number;
  showWatchlistAlertBadges: boolean;
  allowMultipleWatchlists: boolean;
  defaultWatchlistName: string;
  // Positions
  positionsGroupBy: string;
  positionsDefaultSort: string;
  autoCloseAtExpiry: boolean;
}

export const SETTING_DEFAULTS: AppSettings = {
  // General
  defaultPage: "/",
  timezone: "ET",
  dateFormat: "MM/DD/YYYY",
  numberFormat: "US",
  autoRefresh: true,
  autoRefreshInterval: 60,
  // Trading Defaults
  defaultDTE: 45,
  minDTE: 21,
  maxDTE: 60,
  defaultContracts: 1,
  defaultOrderType: "limit",
  slippageTolerance: 5,
  confirmOrders: true,
  preferEvenLots: false,
  // Risk Management
  maxPositionPct: 5,
  maxPortfolioRisk: 20,
  maxSingleLoss: 500,
  stopLossPct: 50,
  marginBuffer: 20,
  maxOpenPositions: 10,
  enforceRiskLimits: true,
  maxCapitalPerTrade: 2000,
  maxTotalCapitalDeployedPct: 50,
  maxLossPerTradePct: 25,
  maxPortfolioDrawdownPct: 10,
  dailyLossLimit: 1000,
  maxPositionsPerSector: 3,
  maxPositionsPerUnderlying: 1,
  maxLosingPositions: 5,
  riskMinDTE: 21,
  riskMaxDTE: 60,
  earningsAvoidanceDays: 5,
  minContractVolume: 10,
  maxBidAskSpreadPct: 10,
  showRiskWarnings: true,
  showPositionSizingSuggestion: true,
  portfolioSize: 50000,
  // Screener
  screenerColumnVisibility: {
    symbol: true,
    price: true,
    changePercent: true,
    volume: true,
    relVol: true,
    marketCap: true,
    sector: true,
    beta: true,
    recommendedOutlook: true,
    opportunityScore: true,
  },
  minOpportunityScoreToShow: 0,
  highConvictionOpportunityScore: 75,
  highConvictionTechnicalScore: 20,
  highConvictionIvScore: 15,
  highConvictionEntryScore: 15,
  highConvictionMomentumScore: 8,
  screenerDefaultSortColumn: "marketCap",
  screenerDefaultSortDirection: "desc",
  screenerDefaultPreset: "All",
  screenerDefaultLiquidity: "all",
  screenerDefaultOutlook: "all",
  showScoreBreakdownTooltip: true,
  showSetupTypeBadge: true,
  showRecommendationBadge: true,
  defaultMinIvRank: 30,
  defaultMinVolume: 500000,
  defaultMinMarketCap: "1B",
  defaultMinOpportunityScore: 50,
  includeETFs: true,
  includeIndices: false,
  minPrice: 5,
  maxPrice: 0,
  minLiquidity: "medium",
  screenerRowsPerPage: 100,
  screenerDefaultTab: "overview",
  showSectorBadge: true,
  showOutlookBadge: true,
  showConvictionBadges: true,
  // Dashboard
  dashboardRefreshInterval: 60,
  showMarketHoursIndicator: true,
  dashboardCompactCards: false,
  moverCount: 5,
  showBreadthBar: true,
  defaultChartPeriod: "1M",
  // Options Chain
  defaultMinDelta: 0.1,
  defaultMaxDelta: 0.5,
  maxBidAskSpread: 0.5,
  minOpenInterest: 100,
  showWeeklyExp: true,
  chainStrikeRange: 5,
  highlightITM: true,
  showGreeks: true,
  showDelta: true,
  showGamma: false,
  showTheta: true,
  showVega: true,
  showRho: false,
  greeksPrecision: 2,
  showPortfolioGreeksSummary: true,
  greeksDisplayFormat: "perContract",
  shortPutDeltaMin: 0.2,
  shortPutDeltaMax: 0.3,
  shortCallDeltaMin: 0.2,
  shortCallDeltaMax: 0.3,
  longOptionDeltaMin: 0.4,
  longOptionDeltaMax: 0.6,
  highlightOutsideTargetDelta: true,
  showDeltaAsProbabilityItm: false,
  ivDisplayFormat: "percent",
  showIvRankAlongsideIv: true,
  showIvPercentileAlongsideIvRank: false,
  ivRankCalculationPeriod: "1Y",
  highlightHighIvStocks: true,
  highIvHighlightThreshold: 60,
  defaultExpirationCount: 4,
  showOpenInterestColumn: true,
  showVolumeColumn: true,
  showBidAskSpreadColumn: true,
  showTheoreticalValueColumn: false,
  filterIlliquidOptionsAutomatically: true,
  showDailyThetaDecay: true,
  showThetaAsDollarsPerDay: true,
  showThetaDecayCurve: false,
  thetaDecayWarningThresholdDte: 21,
  rsiOverbought: 70,
  rsiOversold: 30,
  // Strategy
  enabledStrategyIds: {},
  strategyDefaultOutlook: "all",
  strategyDefaultTier: "all",
  strategyDefaultStrategyId: "",
  preferredIvEnvironment: "any",
  ivRankLowThreshold: 30,
  ivRankHighThreshold: 60,
  strategyAutoSelectByIv: true,
  ivScoreWeight: 25,
  technicalScoreWeight: 35,
  entryScoreWeight: 25,
  momentumScoreWeight: 15,
  vwapScoreWeight: 10,
  preferredStrategies: ["Short Put", "Iron Condor"],
  minCredit: 0.5,
  targetProfitPct: 50,
  maxLossMultiplier: 2,
  showProbabilityOfProfit: true,
  useTheoreticalValue: false,
  // Portfolio & P&L
  pnlMethod: "mark",
  commissionPerContract: 0.65,
  perLegCommission: 0,
  exchangeFeePerContract: 0.1,
  includeCommissionsInPnl: true,
  includeFeesInBreakeven: true,
  contractMultiplier: 100,
  pnlDisplayMode: "both",
  showMaxProfitOnPnlCurve: true,
  showMaxLossOnPnlCurve: true,
  showBreakevenOnPnlCurve: true,
  showCurrentPriceOnPnlCurve: true,
  pnlCurveResolution: 100,
  scenarioUnderlyingMovePct: 5,
  scenarioIvChangePct: 10,
  scenarioDteStepDays: 7,
  showGreeksImpactInScenario: true,
  defaultProfitTargetPct: 50,
  defaultStopLossPct: 100,
  showProfitTargetLine: true,
  showStopLossLine: true,
  autoCalculateProfitTarget: true,
  defaultIvAssumption: "current",
  riskFreeRatePct: 4.5,
  dividendYieldAssumptionPct: 0,
  useHistoricalVolatilityForSimulation: false,
  benchmark: "SPY",
  showUnrealizedPnl: true,
  showRealizedPnl: true,
  taxMethod: "FIFO",
  showPortfolioDelta: true,
  showPortfolioTheta: true,
  // Alerts
  browserNotifications: false,
  soundAlerts: false,
  toastDuration: 3000,
  ivRankAlertThreshold: 60,
  priceMoveAlertPct: 5,
  pnlAlertThreshold: 1000,
  expiryWarningDays: 7,
  earningsAlertDays: 5,
  // Appearance
  theme: "dark",
  uiDensity: "comfortable",
  fontSize: "medium",
  chartStyle: "candlestick",
  animateTransitions: true,
  showMiniCharts: false,
  tableRowHeight: "default",
  sidebarDefaultOpen: true,
  // Data & Sources
  universeMode: "polygon",
  cacheRefreshInterval: 30 * 60 * 1000,
  showDataSourceTags: true,
  polygonRefreshRate: 30,
  marketDataSource: "auto",
  screenerUniverseSize: 1000,
  enablePreMarket: false,
  enableAfterHours: false,
  cacheStrategy: "moderate",
  // Advanced / Security
  debugMode: false,
  apiTimeout: 15000,
  logLevel: "warn",
  disableStreamer: false,
  // Time Horizon
  earningsBlackoutDays: 5,
  showDteRangeFilterDefault: true,
  preferredExpirationCycles: ["weekly", "monthly"],
  highlightPreferredExpirationCycles: true,
  warnOutsidePreferredExpirationCycle: true,
  earningsAvoidanceBeforeDays: 5,
  earningsAvoidanceAfterDays: 1,
  showEarningsDateColumnDefault: true,
  showEarningsWarningBadge: true,
  allowEarningsAvoidanceOverride: false,
  thetaOpenMinDTE: 21,
  thetaOpenMaxDTE: 45,
  thetaCloseProfitPct: 50,
  thetaCloseDTE: 21,
  showThetaDecayChart: true,
  avoidMondayMorningEntries: false,
  avoidFridayAfternoonEntries: false,
  preferredTradingWindowStart: "09:45",
  preferredTradingWindowEnd: "15:45",
  // Chart & Analysis
  defaultChartIndicators: ["SMA20", "SMA50"],
  showVolumeOnChart: true,
  candleInterval: "1D",
  chartHeight: "normal",
  autoFitChartToPrice: true,
  showSMA20: true,
  sma20Color: "#60a5fa",
  showSMA50: true,
  sma50Color: "#f59e0b",
  showSMA200: true,
  sma200Color: "#a78bfa",
  showEMA9: false,
  ema9Color: "#22c55e",
  showEMA21: false,
  ema21Color: "#f97316",
  showVWAPLine: true,
  vwapColor: "#14b8a6",
  showSupportResistanceLines: true,
  showBollingerBands: false,
  showRsiPanel: true,
  showMacdPanel: false,
  showAtrPanel: false,
  show52WeekHighLowLines: true,
  showEarningsMarkersOnChart: true,
  showStrategyPriceLevels: true,
  showPositionPnlOverlay: true,
  showBreakevenLines: true,
  // Watchlist
  maxWatchlistSize: 50,
  showWatchlistSizeWarning: true,
  watchlistSizeWarningThresholdPct: 80,
  allowDuplicateWatchlistSymbols: false,
  autoRemoveLowScoreWatchlistSymbols: false,
  autoRemoveWatchlistScoreThreshold: 40,
  watchlistDefaultSort: "symbol",
  watchlistDefaultSortDirection: "asc",
  watchlistShowOpportunityScore: true,
  watchlistShowSetupTypeBadge: true,
  watchlistShowLastUpdated: true,
  watchlistShowIVRank: true,
  watchlistShowEarnings: true,
  watchlistShowDailyChange: true,
  compactWatchlistView: false,
  autoAddHighConvictionToWatchlist: false,
  autoAddWatchlistOpportunityThreshold: 80,
  autoAddOnlyPreferredStrategies: true,
  maxWatchlistAutoAddsPerDay: 5,
  notifyOnWatchlistAutoAdd: true,
  alertWatchlistScoreDrop: false,
  watchlistScoreDropAlertThreshold: 60,
  watchlistEarningsAlertDays: 5,
  watchlistIvSpikeAlertThreshold: 70,
  showWatchlistAlertBadges: true,
  allowMultipleWatchlists: false,
  defaultWatchlistName: "My Watchlist",
  // Positions
  positionsGroupBy: "none",
  positionsDefaultSort: "openDate",
  autoCloseAtExpiry: false,
};
